DROP TABLE IF EXISTS ALBUM;
DROP TABLE IF EXISTS SINGLE;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS USER_CONFIG;


CREATE TABLE ALBUM (
    ID TEXT PRIMARY KEY,
    TITLE TEXT NOT NULL,
    ARTISTS TEXT NOT NULL,
    GENRE TEXT NOT NULL,
    SUBGENRE TEXT NOT NULL,
    RATING REAL NOT NULL,
    N_TRACKS INTEGER NOT NULL,
    LENGTH REAL NOT NULL,
    DT_RELEASE TEXT NOT NULL,
    DT_INSERTED TEXT NOT NULL
);

CREATE TABLE SINGLE (
    ID TEXT PRIMARY KEY,
    TITLE TEXT NOT NULL,
    ARTISTS TEXT NOT NULL,
    GENRE TEXT NOT NULL,
    SUBGENRE TEXT NOT NULL,
    RATING REAL NOT NULL,
    LENGTH REAL NOT NULL,
    DT_RELEASE TEXT NOT NULL,
    DT_INSERTED TEXT NOT NULL
);

CREATE TABLE USER (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EMAIL TEXT NOT NULL,
    USERNAME TEXT UNIQUE NOT NULL,
    PASSWORD TEXT NOT NULL,
    SCHEMA TEXT NOT NULL
);

CREATE TABLE USER_CONFIG (
    ID_USER INTEGER NOT NULL,
    STYLE INTEGER UNIQUE NOT NULL,
    FOREIGN KEY (ID_USER) REFERENCES USER(ID)
);
